// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD152-yHzwvTj4U9KX36woDZy29jciF4CA',
    appId: '1:602855055632:web:6117f2a1fe2c64b96a4595',
    messagingSenderId: '602855055632',
    projectId: 'project-2566-e0b31',
    authDomain: 'project-2566-e0b31.firebaseapp.com',
    storageBucket: 'project-2566-e0b31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLa5CLGLQgEk1fpHWzONsgSFDio5Mc9A',
    appId: '1:602855055632:android:916fa4a16b50a4f56a4595',
    messagingSenderId: '602855055632',
    projectId: 'project-2566-e0b31',
    storageBucket: 'project-2566-e0b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvr9iVwGt9aF_PSdPlexgh31t04LGCcX0',
    appId: '1:602855055632:ios:a0b7b963fa1f66536a4595',
    messagingSenderId: '602855055632',
    projectId: 'project-2566-e0b31',
    storageBucket: 'project-2566-e0b31.appspot.com',
    iosClientId: '602855055632-eaf7brtg9ea9n9682q1a306b7ukbdtg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2566',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvr9iVwGt9aF_PSdPlexgh31t04LGCcX0',
    appId: '1:602855055632:ios:a0b7b963fa1f66536a4595',
    messagingSenderId: '602855055632',
    projectId: 'project-2566-e0b31',
    storageBucket: 'project-2566-e0b31.appspot.com',
    iosClientId: '602855055632-eaf7brtg9ea9n9682q1a306b7ukbdtg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2566',
  );
}
